apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "teachua.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "teachua.fullname" . }}-frontend-service
            port:
              number: 80
