# templates/mariadb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.mariadb.env.MYSQL_USER | b64enc | quote }}
  password: {{ .Values.mariadb.env.MYSQL_PASSWORD | b64enc | quote }}
  root-password: {{ .Values.mariadb.env.MYSQL_ROOT_PASSWORD | b64enc | quote }}

#data:
#  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.env.MYSQL_ROOT_PASSWORD | b64enc | quote }}
#  MYSQL_DATABASE: {{ .Values.mariadb.env.MYSQL_DATABASE | b64enc | quote }}
#  MYSQL_USER: {{ .Values.mariadb.env.MYSQL_USER | b64enc | quote }}
#  MYSQL_PASSWORD: {{ .Values.mariadb.env.MYSQL_PASSWORD | b64enc | quote }}
