# Default values for teachua.
# This is a YAML-formatted file.
# Declare variables to be passed into my templates.

#namespace: new-namespace

service:
  type: LoadBalancer
  port: 80

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/natvor/teachua-backend-natvor
    tag: latest
  service:
    type: LoadBalancer
  env:
    JDBC_DRIVER: "org.mariadb.jdbc.Driver"
    DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/teachua"
    DATASOURCE_USER: "user"
    DATASOURCE_PASSWORD: "password"
  imagePullSecret: ghcr-secret

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/natvor/teachua-frontend-natvor
    tag: latest
  service:
    type: LoadBalancer
  env:
    REACT_APP_ROOT_SERVER: "http://{{ .Release.Name }}-backend-service:80"
  imagePullSecret: ghcr-secret

mariadb:
  image:
    repository: mariadb
    tag: latest
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
  env:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "teachua"
    MYSQL_USER: "user"
    MYSQL_PASSWORD: "password"

ingress:
  enabled: true
  host: 74.248.85.102.nip.io

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
